// react_to_ng2/src/app/container/container.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'app-container',
  template: `
    <main class="Container">
      <div class="ItemListArea Container__flex">
        <h2>商品一覧 / 品数: 5</h2>
      </div>

      <div class="CartArea">
        <h4>カート</h4>
        <div class="Total">
          計2点
          <span class="Total__price">1600円</span>
        </div>
      </div>
  `,
  styleUrls: ['container.component.css']
})
export class ContainerComponent implements OnInit {

  constructor() {}

  ngOnInit() {
  }

}

// cg_store_props/src/component/Container.jsx
import React from 'react';

import Cart from './Cart.jsx';
import ItemList from './ItemList.jsx';

const Container = (props) => {
  const { listItems } = props;

  return (
    <main className="Container">
      <div className="ItemListArea Container__flex">
        <h2>商品一覧 / 品数: {listItems.length}</h2>
        <ItemList items={listItems} />
      </div>

      <div className="CartArea">
        <h4>カート</h4>
        <Cart items={[]} />
        <div className="Total">
          計0点
          <span className="Total__price">0円</span>
        </div>
      </div>
    </main>
  );
};

Container.propTypes = {
  listItems: React.PropTypes.arrayOf(React.PropTypes.object).isRequired,
};

export default Container;
